name: publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Build release distributions
      run: hatch build

    - name: Upload distributions.
      run: hatch publish
      env:
        HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
